import pexpect
import sys

child = pexpect.spawn("python main.py", encoding="utf-8")
child.logfile = sys.stdout

child.expect("Choose theory.*:")
child.sendline("NT")
child.expect("Enable foundational proof logging.*:")
child.sendline("N")
child.expect("ITP.*> ")
child.sendline("cv x y")
child.expect("ITP.*> ")
child.sendline("def_f 1 P x ι y S y = x")
child.expect("ITP.*> ")
child.sendline("cf goal ∀x P S x = x")
child.expect("ITP.*> ")
child.sendline("mission goal")
child.expect("ITP.*> ")
child.sendline("intro u goal2")
child.expect("ITP.*> ")
child.sendline("fold all goal2 goal3")
child.expect("Enter replacement variable for 'iota \\(first variable\\)':")
child.sendline("v")
child.expect("Enter replacement variable for 'iota \\(second variable\\)':")
child.sendline("w")
child.expect("ITP.*> ")
child.sendline("undo")
child.expect("ITP.*> ")
child.sendline("show")
child.expect("ITP.*> ")
child.sendline("exit")
child.close()
